#spring:
#  config:
#    activate:
#      on-profile: prd
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3308/wz?serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  flyway:
#    enabled: false